## 正则表达式

In [8]:
import re

### 获取包含关键字的字符

In [14]:
str='文本最重要的来源无疑是网络。我们要把网络中的文本获取形成一个文本数据库。利用一个爬虫抓取到网络中的信息。爬取的策略有广度爬取和深度爬取。根据用户的需求，爬虫可以有主题爬虫和通用爬虫之分。'
p_string=str.split('。')

In [18]:
regex='爬虫'
regex2='文本'
for line in p_string:
    if re.search(regex,line) is not None:
        print('regex:'+regex+",line:"+line)
    if re.search(regex2,line) is not None:
        print('regex:'+regex2+",line:"+line)

regex:文本,line:文本最重要的来源无疑是网络
regex:文本,line:我们要把网络中的文本获取形成一个文本数据库
regex:爬虫,line:利用一个爬虫抓取到网络中的信息
regex:爬虫,line:根据用户的需求，爬虫可以有主题爬虫和通用爬虫之分


### 匹配一个任意字符

In [19]:
regex='爬.'
regex2='用户.'
for line in p_string:
    if re.search(regex,line) is not None:
        print('regex:'+regex+",line:"+line)
    if re.search(regex2,line) is not None:
        print('regex:'+regex2+",line:"+line)

regex:爬.,line:利用一个爬虫抓取到网络中的信息
regex:爬.,line:爬取的策略有广度爬取和深度爬取
regex:爬.,line:根据用户的需求，爬虫可以有主题爬虫和通用爬虫之分
regex:用户.,line:根据用户的需求，爬虫可以有主题爬虫和通用爬虫之分


### 匹配起始和结尾字符

In [20]:
regex='^文本'
regex2='信息$'
for line in p_string:
    if re.search(regex,line) is not None:
        print('regex:'+regex+",line:"+line)
    if re.search(regex2,line) is not None:
        print('regex:'+regex2+",line:"+line)

regex:^文本,line:文本最重要的来源无疑是网络
regex:信息$,line:利用一个爬虫抓取到网络中的信息


### 使用中括号匹配多个字符

In [24]:
str=['[重要的]今年第七号台风23日陆广东东部沿海地区','上海发布车库销售监管通知：违规者暂停网签格','[紧要的]中国对印连发强硬信息，印度急切要结東对峙']
regex='^\[[重紧]..\]'
for line in str:
    if re.search(regex,line) is not None:
        print(line)
    else:
        print('no match')

[重要的]今年第七号台风23日陆广东东部沿海地区
no match
[紧要的]中国对印连发强硬信息，印度急切要结東对峙


### 使用转义符

In [28]:
#if re.search('\\\\','I have one nee\dle') is not None:
if re.search(r'\\','I have one nee\dle') is not None:
    print('match it')
else:
    print('not match')

match it


### 抽取文本中的数字

In [30]:
str=['War of 1812','There are 5280 feet to a mile','Happy New Year 2016!']
for s in str:
    if re.search('[1-2][0-9]{3}',s) is not None:
        print(re.findall('[1-2][0-9]{3}',s))
        print(s)
        

['1812']
War of 1812
['2016']
Happy New Year 2016!


## NumPy

In [32]:
import numpy as np

In [34]:
vector=np.array([1,2,3,4])
matrix=np.array([[1,'Tim'],[2,'Joey'],[3,'Johnny'],[4,'Frank']])

In [37]:
a=np.arange(15).reshape(3,5)

In [41]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [40]:
print(a[2,3])

13


In [43]:
print(a==12)

[[False False False False False]
 [False False False False False]
 [False False  True False False]]


In [52]:
a[a[:,2]==12,:]

array([[10, 11, 12, 13, 14]])